apiVersion: v1
kind: Service
metadata:
  name: latency-monitor-service
  labels:
    app: latency-monitor
spec:
  type: {{ .Values.service.type }}
  selector:
    app: latency-monitor
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
